### ISSUE TITLE
[help needed] Long translation for lobby title

### ISSUE THREAD

**Issue by Blueberryy** [ReactiveDrop/reactivedrop_translations#1703]
Translations for some languages overlap `"Lobby leader: *player name*"` that goes after `"MISSION PREP"`.
Here's languages and screenshots showing the problem;

**Brazilian**
![image](https://github.com/user-attachments/assets/ff5437d0-78a4-4dce-a724-4034d86cc5a2)
**Danish**
![image](https://github.com/user-attachments/assets/93c204d7-2cbd-4eb5-9024-5aa65f96b5a5)
**Finnish**
![image](https://github.com/user-attachments/assets/b4e692d2-7253-449c-8696-4452e286bed1)
**Latam**
![image](https://github.com/user-attachments/assets/c20039e1-6d69-4e89-a20d-a6d678b484ad)
**Spanish**
![image](https://github.com/user-attachments/assets/ef3e5e4f-fb15-41d2-a955-13ff5834a847)

- [x] **Brazilian** - @Tarkoviski and @FurtadoPires (or anyone). [#1706]
- [x] **Danish** - Anyone. [#1704]
- [x] **Finnish** - @Crazymanbos (or anyone). [#1704]
- [x] **Latam** - @gaelcoral and @Bravepotato95 (or anyone). [#1792]
- [x] **Spanish** - @Bravepotato95 (or anyone). [#1792]
; please shorten translation of "MISSION PREP" if you find time. Or you can use alternative translation and retranslate it as "Preparation" or "Lobby". Thanks for your contribution!

You can see how to contribute translation [here](https://github.com/ReactiveDrop/reactivedrop_translations/blob/master/CONTRIBUTING.md), or you can contact me through Discord `theonlyoneblueberry` and send edited translation files there if you don't want to mess with GIthub stuff.

**Comment by Duke-M-commits** [comment]
That's one of many ui-scale issues we have, i believe that should go here: https://github.com/ReactiveDrop/reactivedrop_translations/discussions/497
Shortening the strings is an obvious solution (i did that same in my translation a long time ago). But in the end - especially if the issue exists for multiple languages - that is something an better ui should handle. Not every meaning can be shortened down in all supported languages.
Here's an good example from the forum:
![218036189-a747b973-14d9-44ec-8a1e-84e0c415bf77](https://github.com/user-attachments/assets/28ad2f78-7cd1-4c6b-8571-cdc09259fc76)
"Difficulty", translated into german, just cannot get shorter, there is nothing which i can do about it. And "Mission Prep" is just another one of these longer wordings, funny enough even in the english original version it's already "Prep" for "Preperation" because not even the original devs had enough space available.

**Comment by Crazymanbos** [comment]
Working on it! Will return later (hopefully with results)

**Comment by Crazymanbos** [comment]
I could fix the Danish version too, its close to swedish. Just remove the word missions and it means preparation basically, it should be short enough.

**Comment by Crazymanbos** [comment]
Alr, Danish and Finnish is fixed!

**Comment by Blueberryy** [comment]
> That's one of many ui-scale issues we have, i believe that should go into this discussion: https://github.com/ReactiveDrop/reactivedrop_translations/discussions/497
> Shortening the strings is an obvious solution (i did that same in my translation a long time ago). But in the end - especially if the issue exists for multiple languages - that is something an better ui should handle. Not every meaning can be shortened down in all supported languages.
> Here's an good example from the linked discussion:
> ![218036189-a747b973-14d9-44ec-8a1e-84e0c415bf77](https://github.com/user-attachments/assets/28ad2f78-7cd1-4c6b-8571-cdc09259fc76)
> "Difficulty", translated into german, just cannot get shorter, there is nothing which i can do about it. And "Mission Prep" is just another one of these longer wordings, funny enough even in the english original version it's already "Prep" for "Preperation" because not even the original devs had enough space available.

Yeah maybe in further anniversary updates game will receive revamped UI and auto-scrollable text feature when you hover cursor on specific places.

**Comment by Crazymanbos** [comment]
I think prep is good enough wording. The players gotta understand its prep for the mission, they would just find out anyway when beating the mission anyway that next mission lets them change gear before ready up

**Comment by FurtadoPires** [comment]
@Blueberryy I'll be handle this one, any problems if I abbreviate?

**Comment by Blueberryy** [comment]
> @Blueberryy I'll handle this one, any problems if I abbreviate?

Yeah that would do.

**Comment by Bravepotato95** [comment]
Hello everyone. I have made a pull request to reduce the length of that text for both latam and spanish.
The pull request is:
https://github.com/ReactiveDrop/reactivedrop_translations/pull/1792
Thank you very much and best regards.
